export type CurrencySymbol = keyof typeof CURRENCY_MAP;
export const CURRENCY_MAP  = 
  {
    BTC: { name: 'Bitcoin', icon: 'https://cryptologos.cc/thumbs/bitcoin.png' },
    ETH: { name: 'Ethereum', icon: 'https://cryptologos.cc/thumbs/ethereum.png' },
    USDT: { name: 'Tether USD', icon: 'https://cryptologos.cc/thumbs/tether.png' },
    USDC: { name: 'USD Coin', icon: 'https://cryptologos.cc/thumbs/usd-coin.png' },
    BNB: { name: 'Binance Coin', icon: 'https://cryptologos.cc/thumbs/binance-usd.png' },
    XRP: { name: 'XRP', icon: 'https://cryptologos.cc/thumbs/xrp.png' },
    ADA: { name: 'Cardano', icon: 'https://cryptologos.cc/thumbs/cardano.png' },
    SOL: { name: 'Solana', icon: 'https://cryptologos.cc/thumbs/solana.png' },
    DOGE: { name: 'Dogecoin', icon: 'https://cryptologos.cc/thumbs/dogecoin.png' },
    DOT: { name: 'Polkadot', icon: 'https://cryptologos.cc/thumbs/polkadot-new.png' },
    MATIC: { name: 'Polygon', icon: 'https://cryptologos.cc/thumbs/polygon.png' },
    AVAX: { name: 'Avalanche', icon: 'https://cryptologos.cc/thumbs/Avalanche.png' },
    TRX: { name: 'TRON', icon: 'https://cryptologos.cc/thumbs/tron.png' },
    LTC: { name: 'Litecoin', icon: 'https://cryptologos.cc/thumbs/litecoin.png' },
    BCH: { name: 'Bitcoin Cash', icon: 'https://cryptologos.cc/thumbs/bitcoin-cash.png' },
    LINK: { name: 'Chainlink', icon: 'https://cryptologos.cc/thumbs/chainlink.png' },
    ATOM: { name: 'Cosmos', icon: 'https://cryptologos.cc/thumbs/cosmos.png' },
    XLM: { name: 'Stellar', icon: 'https://cryptologos.cc/thumbs/stellar.png' },
    ETC: { name: 'Ethereum Classic', icon: 'https://cryptologos.cc/thumbs/ethereum-classic.png' },
    XMR: { name: 'Monero', icon: 'https://cryptologos.cc/thumbs/monero.png' },
    EOS: { name: 'EOS', icon: 'https://cryptologos.cc/thumbs/eos.png' },
    NEO: { name: 'NEO', icon: 'https://cryptologos.cc/thumbs/neo.png' },
    XTZ: { name: 'Tezos', icon: 'https://cryptologos.cc/thumbs/tezos.png' },
    VET: { name: 'VeChain', icon: 'https://cryptologos.cc/thumbs/vechain.png' },
    ALGO: { name: 'Algorand', icon: 'https://cryptologos.cc/thumbs/algorand.png' },
    FIL: { name: 'Filecoin', icon: 'https://cryptologos.cc/thumbs/filecoin.png' },
    ICP: { name: 'Internet Computer', icon: 'https://cryptologos.cc/thumbs/internet-computer.png' },
    AAVE: { name: 'Aave', icon: 'https://cryptologos.cc/thumbs/aave.png' },
    UNI: { name: 'Uniswap', icon: 'https://cryptologos.cc/thumbs/uniswap.png' },
    SUSHI: { name: 'SushiSwap', icon: 'https://cryptologos.cc/thumbs/sushiswap.png' },
    SHIB: { name: 'Shiba Inu', icon: 'https://cryptologos.cc/thumbs/shiba-inu.png' },
    HBAR: { name: 'Hedera', icon: 'https://cryptologos.cc/thumbs/hedera.png' },
    NEAR: { name: 'NEAR Protocol', icon: 'https://cryptologos.cc/thumbs/near-protocol.png' },
    FTM: { name: 'Fantom', icon: 'https://cryptologos.cc/thumbs/fantom.png' },
    KSM: { name: 'Kusama', icon: 'https://cryptologos.cc/thumbs/kusama.png' },
    OKB: { name: 'OKB', icon: 'https://cryptologos.cc/thumbs/okb.png' },
    LEO: { name: 'UNUS SED LEO', icon: 'https://cryptologos.cc/thumbs/unus-sed-leo.png' },
    THETA: { name: 'Theta Network', icon: 'https://cryptologos.cc/thumbs/theta-network.png' },
    GALA: { name: 'Gala', icon: 'https://cryptologos.cc/thumbs/gala.png' },
    SAND: { name: 'The Sandbox', icon: 'https://cryptologos.cc/thumbs/the-sandbox.png' },
    MANA: { name: 'Decentraland', icon: 'https://cryptologos.cc/thumbs/decentraland.png' },
    AXS: { name: 'Axie Infinity', icon: 'https://cryptologos.cc/thumbs/axie-infinity.png' },
    APT: { name: 'Aptos', icon: 'https://cryptologos.cc/thumbs/aptos.png' },
    SUI: { name: 'Sui', icon: 'https://cryptologos.cc/thumbs/sui.png' },
    TON: { name: 'Toncoin', icon: 'https://cryptologos.cc/thumbs/toncoin.png' },
    ARB: { name: 'Arbitrum', icon: 'https://cryptologos.cc/thumbs/arbitrum.png' },
    OP: { name: 'Optimism', icon: 'https://cryptologos.cc/thumbs/optimism-ethereum.png' },
    B2M: { name: 'Bit2Me', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/13901.png' },
    ZIL: { name: 'Zilliqa', icon: 'https://cryptologos.cc/thumbs/zilliqa.png' },
    EQL: { name: 'Equalizer', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6780.png' },
    FARMS: { name: 'Farms', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/33955.png' },
    BAT: { name: 'Basic Attention Token', icon: 'https://cryptologos.cc/thumbs/basic-attention-token.png' },
    REP: { name: 'Augur', icon: 'https://cryptologos.cc/thumbs/augur.png' },
    ZRX: { name: '0x', icon: 'https://cryptologos.cc/thumbs/0x.png' },
    DAI: { name: 'Dai', icon: 'https://cryptologos.cc/thumbs/multi-collateral-dai.png' },
    DASH: { name: 'Dash', icon: 'https://cryptologos.cc/thumbs/dash.png' },
    SWTH: { name: 'Switcheo', icon: 'https://cryptologos.cc/thumbs/switcheo.png' },
    ZEC: { name: 'Zcash', icon: 'https://cryptologos.cc/thumbs/zcash.png' },
    YEC: { name: 'Ycash', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4160.png' },
    BTG: { name: 'Bitcoin Gold', icon: 'https://cryptologos.cc/thumbs/bitcoin-gold.png' },
    NANO: { name: 'Nano', icon: 'https://cryptologos.cc/thumbs/nano.png' },
    WAVES: { name: 'Waves', icon: 'https://cryptologos.cc/thumbs/waves.png' },
    KMD: { name: 'Komodo', icon: 'https://cryptologos.cc/thumbs/komodo.png' },
    AE: { name: 'Aeternity', icon: 'https://cryptologos.cc/thumbs/aeternity.png' },
    RSK: { name: 'RSK', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3701.png' },
    WAN: { name: 'Wanchain', icon: 'https://cryptologos.cc/thumbs/wanchain.png' },
    STRAT: { name: 'Stratis', icon: 'https://cryptologos.cc/thumbs/stratis.png' },
    UBQ: { name: 'Ubiq', icon: 'https://cryptologos.cc/thumbs/ubiq.png' },
    IOTA: { name: 'IOTA', icon: 'https://cryptologos.cc/thumbs/iota.png' },
    QTUM: { name: 'Qtum', icon: 'https://cryptologos.cc/thumbs/qtum.png' },
    ICX: { name: 'Icon', icon: 'https://cryptologos.cc/thumbs/icon.png' },
    DGB: { name: 'Digibyte', icon: 'https://cryptologos.cc/thumbs/digibyte.png' },
    XZC: { name: 'Zcoin', icon: 'https://cryptologos.cc/thumbs/zcoin.png' },
    FIRO: { name: 'Firo', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1414.png' },
    BURST: { name: 'Burstcoin', icon: 'https://cryptologos.cc/thumbs/burst.png' },
    DCR: { name: 'Decred', icon: 'https://cryptologos.cc/thumbs/decred.png' },
    XEM: { name: 'NEM', icon: 'https://cryptologos.cc/thumbs/nem.png' },
    LSK: { name: 'Lisk', icon: 'https://cryptologos.cc/thumbs/lisk.png' },
    ONG: { name: 'Ontology Gas', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3217.png' },
    ONT: { name: 'Ontology', icon: 'https://cryptologos.cc/thumbs/ontology.png' },
    SMART: { name: 'Smartcash', icon: 'https://cryptologos.cc/thumbs/smartcash.png' },
    TPAY: { name: 'TokenPay', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2627.png' },
    GRS: { name: 'Groestlcoin', icon: 'https://cryptologos.cc/thumbs/groestlcoin.png' },
    BSV: { name: 'Bitcoin SV', icon: 'https://cryptologos.cc/thumbs/bitcoin-sv.png' },
    GAS: { name: 'GAS', icon: 'https://cryptologos.cc/thumbs/gas.png' },
    VTHO: { name: 'VeThor Token', icon: 'https://cryptologos.cc/thumbs/vethor-token.png' },
    BCD: { name: 'Bitcoin Diamond', icon: 'https://cryptologos.cc/thumbs/bitcoin-diamond.png' },
    BTT: { name: 'BitTorrent', icon: 'https://cryptologos.cc/thumbs/bittorrent.png' },
    KIN: { name: 'Kin', icon: 'https://cryptologos.cc/thumbs/kin.png' },
    RVN: { name: 'Ravencoin', icon: 'https://cryptologos.cc/thumbs/ravencoin.png' },
    ARK: { name: 'Ark', icon: 'https://cryptologos.cc/thumbs/ark.png' },
    XVG: { name: 'Verge', icon: 'https://cryptologos.cc/thumbs/verge.png' },
    NEBL: { name: 'Neblio', icon: 'https://cryptologos.cc/thumbs/neblio.png' },
    XPM: { name: 'Primecoin', icon: 'https://cryptologos.cc/thumbs/primecoin.png' },
    ONE: { name: 'Harmony', icon: 'https://cryptologos.cc/thumbs/harmony.png' },
    BNTY: { name: 'Bounty0x', icon: 'https://cryptologos.cc/thumbs/bounty0x.png' },
    CRO: { name: 'Cronos', icon: 'https://cryptologos.cc/thumbs/cronos.png' },
    TWT: { name: 'Trust Wallet Token', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5964.png' },
    SIERRA: { name: 'Sierra', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/10233.png' },
    VSYS: { name: 'V Systems', icon: 'https://cryptologos.cc/thumbs/v-systems.png' },
    HIVE: { name: 'Hive', icon: 'https://cryptologos.cc/thumbs/hive.png' },
    HT: { name: 'Huobi Token', icon: 'https://cryptologos.cc/thumbs/huobi-token.png' },
    ENJ: { name: 'Enjin Coin', icon: 'https://cryptologos.cc/thumbs/enjin-coin.png' },
    YFI: { name: 'Yearn Finance', icon: 'https://cryptologos.cc/thumbs/yearn-finance.png' },
    MTA: { name: 'Meta', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5748.png' },
    COMP: { name: 'Compound', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    BAL: { name: 'Balancer', icon: 'https://cryptologos.cc/thumbs/balancer.png' },
    AMPL: { name: 'Ampleforth', icon: 'https://cryptologos.cc/thumbs/ampleforth.png' },
    LEND: { name: 'Lend', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/22692.png' },
    TLOS: { name: 'Telos', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4660.png' },
    XDC: { name: 'XinFin', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2634.png' },
    XST: { name: 'Stealth', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/448.png' },
    STRAX: { name: 'Strax', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/30168.png' },
    SIGNA: { name: 'Signa', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/10776.png' },
    NIM: { name: 'Nimiq', icon: 'https://cryptologos.cc/thumbs/nimiq.png' },
    GUAP: { name: 'Guap', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5088.png' },
    YLD: { name: 'Yield', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8066.png' },
    OKT: { name: 'OKChain Token', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8267.png' },
    ELA: { name: 'Elastos', icon: 'https://cryptologos.cc/thumbs/elastos.png' },
    WETH: { name: 'Wrapped Ethereum', icon: 'https://cryptologos.cc/thumbs/ethereum.png' },
    CEL: { name: 'Celsius', icon: 'https://cryptologos.cc/thumbs/celsius.png' },
    CUSDC: { name: 'Compound USDC', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    CETH: { name: 'Compound Ether', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    CDAI: { name: 'Compound Dai', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    AMP: { name: 'Amp', icon: 'https://cryptologos.cc/thumbs/amp.png' },
    CAKE: { name: 'PancakeSwap', icon: 'https://cryptologos.cc/thumbs/pancakeswap.png' },
    MIOTA: { name: 'IOTA', icon: 'https://cryptologos.cc/thumbs/iota.png' },
    FTT: { name: 'FTX Token', icon: 'https://cryptologos.cc/thumbs/ftx-token.png' },
    MKR: { name: 'Maker', icon: 'https://cryptologos.cc/thumbs/maker.png' },
    TFUEL: { name: 'Theta Fuel', icon: 'https://cryptologos.cc/thumbs/theta-fuel.png' },
    KLAY: { name: 'Klaytn', icon: 'https://cryptologos.cc/thumbs/klaytn.png' },
    LUNA: { name: 'Terra Luna', icon: 'https://cryptologos.cc/thumbs/terra-luna.png' },
    SAFEMOON: { name: 'SafeMoon', icon: 'https://cryptologos.cc/thumbs/safemoon.png' },
    UST: { name: 'Terra USD', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7129.png' },
    RUNE: { name: 'THORChain', icon: 'https://cryptologos.cc/thumbs/thorchain.png' },
    TEL: { name: 'Telcoin', icon: 'https://cryptologos.cc/thumbs/telcoin.png' },
    CHZ: { name: 'Chiliz', icon: 'https://cryptologos.cc/thumbs/chiliz.png' },
    EGLD: { name: 'Elrond', icon: 'https://cryptologos.cc/thumbs/elrond.png' },
    TUSD: { name: 'TrueUSD', icon: 'https://cryptologos.cc/thumbs/trueusd.png' },
    HBTC: { name: 'Huobi BTC', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6941.png' },
    SNX: { name: 'Synthetix', icon: 'https://cryptologos.cc/thumbs/synthetix.png' },
    HOT: { name: 'Holo', icon: 'https://cryptologos.cc/thumbs/holo.png' },
    HNT: { name: 'Helium', icon: 'https://cryptologos.cc/thumbs/helium.png' },
    STETH: { name: 'Lido Staked Ether', icon: 'https://cryptologos.cc/thumbs/steth.png' },
    NEXO: { name: 'Nexo', icon: 'https://cryptologos.cc/thumbs/nexo.png' },
    PAX: { name: 'Paxos Standard', icon: 'https://cryptologos.cc/thumbs/paxos-standard.png' },
    STX: { name: 'Stacks', icon: 'https://cryptologos.cc/thumbs/stacks.png' },
    MDX: { name: 'Mdex', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8335.png' },
    ZEN: { name: 'Horizen', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1698.png' },
    ARRR: { name: 'Pirate Chain', icon: 'https://cryptologos.cc/thumbs/pirate-chain.png' },
    BNT: { name: 'Bancor', icon: 'https://cryptologos.cc/thumbs/bancor.png' },
    LUSD: { name: 'Liquity USD', icon: 'https://cryptologos.cc/thumbs/liquity.png' },
    GRT: { name: 'The Graph', icon: 'https://cryptologos.cc/thumbs/the-graph.png' },
    SC: { name: 'Siacoin', icon: 'https://cryptologos.cc/thumbs/siacoin.png' },
    HUSD: { name: 'HUSD', icon: 'https://cryptologos.cc/thumbs/husd.png' },
    CRV: { name: 'Curve', icon: 'https://cryptologos.cc/thumbs/curve-dao-token.png' },
    UMA: { name: 'UMA', icon: 'https://cryptologos.cc/thumbs/uma.png' },
    WRX: { name: 'Wazirx', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5161.png' },
    AR: { name: 'Arweave', icon: 'https://cryptologos.cc/thumbs/arweave.png' },
    OMG: { name: 'OMG Network', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1808.png' },
    GT: { name: 'Gatetoken', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4269.png' },
    QNT: { name: 'Quant', icon: 'https://cryptologos.cc/thumbs/quant.png' },
    CHSB: { name: 'SwissBorg', icon: 'https://cryptologos.cc/thumbs/swissborg.png' },
    IOST: { name: 'IOST', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2405.png' },
    NXM: { name: 'NXM', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5830.png' },
    KCS: { name: 'KuCoin Token', icon: 'https://cryptologos.cc/thumbs/kucoin-token.png' },
    LPT: { name: 'Livepeer', icon: 'https://cryptologos.cc/thumbs/livepeer.png' },
    XSUSHI: { name: 'xSushiSwap', icon: 'https://cryptologos.cc/thumbs/sushiswap.png' },
    CUSDT: { name: 'Compound USDT', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    FLOW: { name: 'Flow', icon: 'https://cryptologos.cc/thumbs/flow.png' },
    ANKR: { name: 'Ankr', icon: 'https://cryptologos.cc/thumbs/ankr.png' },
    HBC: { name: 'HBC', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/35069.png' },
    VGX: { name: 'Voyager Token', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1817.png' },
    FEI: { name: 'Fei', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8642.png' },
    BAKE: { name: 'BakeryToken', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7064.png' },
    '1INCH': { name: '1inch', icon: 'https://cryptologos.cc/thumbs/1inch.png' },
    CKB: { name: 'Nervos', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4948.png' },
    WOO: { name: 'Woo Network', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7501.png' },
    TITAN: { name: 'Titan', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3913.png' },
    OMI: { name: 'Ecomi', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/19075.png' },
    MINA: { name: 'Mina', icon: 'https://cryptologos.cc/thumbs/mina.png' },
    SETH: { name: 'sETH', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5765.png' },
    RSR: { name: 'Reserve Rights', icon: 'https://cryptologos.cc/thumbs/reserve-rights.png' },
    OXY: { name: 'Oxygen', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8029.png' },
    REN: { name: 'Ren', icon: 'https://cryptologos.cc/thumbs/ren.png' },
    XCH: { name: 'Chia', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/9258.png' },
    RENBTC: { name: 'Ren Bitcoin', icon: 'https://cryptologos.cc/thumbs/ren.png' },
    USDN: { name: 'SMARDEX USD', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/35672.png' },
    BCHA: { name: 'Bitcoin ABC', icon: 'https://cryptologos.cc/thumbs/bitcoin-cash.png' },
    LRC: { name: 'Loopring', icon: 'https://cryptologos.cc/thumbs/loopring.png' },
    PUNDIX: { name: 'Pundi X', icon: 'https://cryptologos.cc/thumbs/pundi-x.png' },
    ERG: { name: 'Ergo', icon: 'https://cryptologos.cc/thumbs/ergo.png' },
    WIN: { name: 'WINkLink', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4206.png' },
    NPXS: { name: 'Pundi X NEM', icon: 'https://cryptologos.cc/thumbs/pundi-x.png' },
    TRIBE: { name: 'Tribe', icon: 'https://cryptologos.cc/thumbs/tribe.png' },
    MAID: { name: 'MaidSafeCoin', icon: 'https://cryptologos.cc/thumbs/maidsafecoin.png' },
    ASD: { name: 'Asd', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3673.png' },
    CUNI: { name: 'Compound UNI', icon: 'https://cryptologos.cc/thumbs/compound.png' },
    CELO: { name: 'Celo', icon: 'https://cryptologos.cc/thumbs/celo.png' },
    DENT: { name: 'Dent', icon: 'https://cryptologos.cc/thumbs/dent.png' },
    SNT: { name: 'Status', icon: 'https://cryptologos.cc/thumbs/status.png' },
    FEG: { name: 'FEG Token', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/32074.png' },
    SKL: { name: 'SKALE', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5691.png' },
    ALUSD: { name: 'Alchemix USD', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8613.png' },
    MIR: { name: 'Mirror', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7857.png' },
    GLM: { name: 'Golem', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1455.png' },
    PAXG: { name: 'Pax Gold', icon: 'https://cryptologos.cc/thumbs/pax-gold.png' },
    CFX: { name: 'Conflux', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7334.png' },
    UOS: { name: 'Ultra', icon: 'https://cryptologos.cc/thumbs/ultra.png' },
    SVCS: { name: 'Services', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4052.png' },
    REEF: { name: 'Reef', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6951.png' },
    GNO: { name: 'Gnosis', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1659.png' },
    USDP: { name: 'USDP', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8886.png' },
    KAVA: { name: 'Kava', icon: 'https://cryptologos.cc/thumbs/kava.png' },
    ALCX: { name: 'Alchemix', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8613.png' },
    EWT: { name: 'Energy Web', icon: 'https://cryptologos.cc/thumbs/energy-web-token.png' },
    RLC: { name: 'iExec RLC', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1637.png' },
    AUDIO: { name: 'Audius', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7455.png' },
    XVS: { name: 'Venus', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7288.png' },
    BAND: { name: 'Band Protocol', icon: 'https://cryptologos.cc/thumbs/band-protocol.png' },
    NMR: { name: 'Numeraire', icon: 'https://cryptologos.cc/thumbs/numeraire.png' },
    INJ: { name: 'Injective', icon: 'https://cryptologos.cc/thumbs/injective.png' },
    WAXP: { name: 'WAX', icon: 'https://cryptologos.cc/thumbs/wax.png' },
    UQC: { name: 'Uquid Coin', icon: 'https://cryptologos.cc/thumbs/uquid-coin.png' },
    IOTX: { name: 'IoTeX', icon: 'https://cryptologos.cc/thumbs/iotex.png' },
    FUN: { name: 'FunFair', icon: 'https://cryptologos.cc/thumbs/funfair.png' },
    OCEAN: { name: 'Ocean Protocol', icon: 'https://cryptologos.cc/thumbs/ocean-protocol.png' },
    CTSI: { name: 'Cartesi', icon: 'https://cryptologos.cc/thumbs/cartesi.png' },
    RAY: { name: 'Raydium', icon: 'https://cryptologos.cc/thumbs/raydium.png' },
    ANC: { name: 'Anchor Protocol', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8857.png' },
    IQ: { name: 'Everipedia', icon: 'https://cryptologos.cc/thumbs/everipedia.png' },
    SUSD: { name: 'sUSD', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2927.png' },
    KLV: { name: 'Klever', icon: 'https://cryptologos.cc/thumbs/klever.png' },
    BTCST: { name: 'Bitcoin Standard Hashrate Token', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8891.png' },
    TLM: { name: 'Alien Worlds', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/9119.png' },
    AKT: { name: 'Akash', icon: 'https://cryptologos.cc/thumbs/akash.png' },
    STMX: { name: 'StormX', icon: 'https://cryptologos.cc/thumbs/stormx.png' },
    PROM: { name: 'Prometheus', icon: 'https://cryptologos.cc/thumbs/prometheus.png' },
    XPRT: { name: 'Persistence', icon: 'https://cryptologos.cc/thumbs/persistence.png' },
    SRM: { name: 'Serum', icon: 'https://cryptologos.cc/thumbs/serum.png' },
    RPL: { name: 'Rocket Pool', icon: 'https://cryptologos.cc/thumbs/rocket-pool.png' },
    AGIX: { name: 'SingularityNET', icon: 'https://cryptologos.cc/thumbs/singularitynet.png' },
    CELR: { name: 'Celer Network', icon: 'https://cryptologos.cc/thumbs/celer-network.png' },
    FET: { name: 'Fetch.ai', icon: 'https://cryptologos.cc/thumbs/fetch-ai.png' },
    OXT: { name: 'Orchid', icon: 'https://cryptologos.cc/thumbs/orchid.png' },
    ARDR: { name: 'Ardor', icon: 'https://cryptologos.cc/thumbs/ardor.png' },
    MATH: { name: 'Mathwallet', icon: 'https://cryptologos.cc/thumbs/mathwallet.png' },
    '10SET': { name: 'Tenset', icon: 'https://cryptologos.cc/thumbs/tenset.png' },
    POLY: { name: 'Polymath', icon: 'https://cryptologos.cc/thumbs/polymath.png' },
    GUSD: { name: 'Gemini Dollar', icon: 'https://cryptologos.cc/thumbs/gemini-dollar.png' },
    NKN: { name: 'NKN', icon: 'https://cryptologos.cc/thumbs/nkn.png' },
    CVC: { name: 'Civic', icon: 'https://cryptologos.cc/thumbs/civic.png' },
    GTC: { name: 'Gitcoin', icon: 'https://cryptologos.cc/thumbs/gitcoin.png' },
    STEEM: { name: 'Steem', icon: 'https://cryptologos.cc/thumbs/steem.png' },
    ORN: { name: 'Orion Protocol', icon: 'https://cryptologos.cc/thumbs/orion-protocol.png' },
    KEEP: { name: 'Keep Network', icon: 'https://cryptologos.cc/thumbs/keep-network.png' },
    HXRO: { name: 'HXRO', icon: 'https://cryptologos.cc/thumbs/hxro.png' },
    ORBS: { name: 'Orbs', icon: 'https://cryptologos.cc/thumbs/orbs.png' },
    ALPHA: { name: 'Alpha Finance', icon: 'https://cryptologos.cc/thumbs/alpha-finance.png' },
    MCONTENT: { name: 'Metacontent', icon: 'https://cryptologos.cc/thumbs/metacontent.png' },
    DODO: { name: 'DODO', icon: 'https://cryptologos.cc/thumbs/dodo.png' },
    OGN: { name: 'Origin Token', icon: 'https://cryptologos.cc/thumbs/origin-protocol.png' },
    KNCL: { name: 'Kyber Network Crystal', icon: 'https://cryptologos.cc/thumbs/kyber-network.png' },
    MED: { name: 'Medibloc', icon: 'https://cryptologos.cc/thumbs/medibloc.png' },
    XAUT: { name: 'Tether Gold', icon: 'https://cryptologos.cc/thumbs/tether-gold.png' },
    VLX: { name: 'Velas', icon: 'https://cryptologos.cc/thumbs/velas.png' },
    PHA: { name: 'Phala Network', icon: 'https://cryptologos.cc/thumbs/phala-network.png' },
    KOBE: { name: 'Kobecoin', icon: 'https://cryptologos.cc/thumbs/kobecoin.png' },
    PERP: { name: 'Perpetual Protocol', icon: 'https://cryptologos.cc/thumbs/perpetual-protocol.png' },
    XHV: { name: 'Haven Protocol', icon: 'https://cryptologos.cc/thumbs/haven-protocol.png' },
    META: { name: 'Metadium', icon: 'https://cryptologos.cc/thumbs/metadium.png' },
    SEUR: { name: 'sEUR', icon: 'https://cryptologos.cc/thumbs/seur.png' },
    MONA: { name: 'MonaCoin', icon: 'https://cryptologos.cc/thumbs/monacoin.png' },
    ANT: { name: 'Aragon', icon: 'https://cryptologos.cc/thumbs/aragon.png' },
    HYDRA: { name: 'Hydra', icon: 'https://cryptologos.cc/thumbs/hydra.png' },
    ZKS: { name: 'zkSync', icon: 'https://cryptologos.cc/thumbs/zksync.png' },
    SXP: { name: 'Swipe', icon: 'https://cryptologos.cc/thumbs/swipe.png' },
    CSPR: { name: 'Casper', icon: 'https://cryptologos.cc/thumbs/casper.png' },
    MTL: { name: 'Metal', icon: 'https://cryptologos.cc/thumbs/metal.png' },
    NU: { name: 'NuCypher', icon: 'https://cryptologos.cc/thumbs/nucypher.png' },
    ZMT: { name: 'Zenith Coin', icon: 'https://cryptologos.cc/thumbs/zenith.png' },
    LOC: { name: 'LockTrip', icon: 'https://cryptologos.cc/thumbs/locktrip.png' },
    TKO: { name: 'Tokocrypto', icon: 'https://cryptologos.cc/thumbs/tokocrypto.png' },
    ETN: { name: 'Electroneum', icon: 'https://cryptologos.cc/thumbs/electroneum.png' },
    UBT: { name: 'Unibright', icon: 'https://cryptologos.cc/thumbs/unibright.png' },
    EXRD: { name: 'Exrdium', icon: 'https://cryptologos.cc/thumbs/exrdium.png' },
    NMX: { name: 'Nominex', icon: 'https://cryptologos.cc/thumbs/nominex.png' },
    RIF: { name: 'Rootstock Infrastructure Framework', icon: 'https://cryptologos.cc/thumbs/rif.png' },
    STORJ: { name: 'Storj', icon: 'https://cryptologos.cc/thumbs/storj.png' },
    AVA: { name: 'Travala', icon: 'https://cryptologos.cc/thumbs/travala.png' },
    DPI: { name: 'DeFi Pulse Index', icon: 'https://cryptologos.cc/thumbs/dpi.png' },
    DOG: { name: 'Dog', icon: 'https://cryptologos.cc/thumbs/dog.png' },
    MOBX: { name: 'Mobius', icon: 'https://cryptologos.cc/thumbs/mobius.png' },
    FAB: { name: 'Fabwelt', icon: 'https://cryptologos.cc/thumbs/fabwelt.png' },
    BEAM: { name: 'Beam', icon: 'https://cryptologos.cc/thumbs/beam.png' },
    DESO: { name: 'DESO', icon: 'https://cryptologos.cc/thumbs/deso.png' },
    FLR: { name: 'Flare', icon: 'https://cryptologos.cc/thumbs/flare.png' },
    SGB: { name: 'Songbird', icon: 'https://cryptologos.cc/thumbs/songbird.png' },
    '0ZK': { name: '0x Zk', icon: 'https://cryptologos.cc/thumbs/0x-zk.png' },
    MOON: { name: 'Mooncoin', icon: 'https://cryptologos.cc/thumbs/mooncoin.png' },
    SWEAT: { name: 'Sweatcoin', icon: 'https://cryptologos.cc/thumbs/sweatcoin.png' },
    POKT: { name: 'Pocket Network', icon: 'https://cryptologos.cc/thumbs/pocket-network.png' },
    KAI: { name: 'Kai Chain', icon: 'https://cryptologos.cc/thumbs/kai-chain.png' },
    XLA: { name: 'Stellar', icon: 'https://cryptologos.cc/thumbs/stellar.png' },
    GTH: { name: 'Gather', icon: 'https://cryptologos.cc/thumbs/gather.png' },
    HI: { name: 'HI Dollar', icon: 'https://cryptologos.cc/thumbs/hi-dollar.png' },
    VERSE: { name: 'VersePay', icon: 'https://cryptologos.cc/thumbs/versepay.png' },
    NIBI: { name: 'Nibiru', icon: 'https://cryptologos.cc/thumbs/nibiru.png' },
    FUSE: { name: 'Fuse', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5634.png' },
    BUSD: {name: "BUSD", icon: "https://cryptologos.cc/thumbs/binance-usd.png"},
    WBTC: {name: "WBTC", icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/3717.png"},
    BLOCKS: {name: "BLOCKS", icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/20918.png"},
    BASE: {name: "BASE",icon:"https://s2.coinmarketcap.com/static/img/rwa/64x64/6878a430cbbf471de336748e.png"},
    FTN: {name: "FTN",icon:"https://s2.coinmarketcap.com/static/img/coins/64x64/22615.png"},
    
  } as const;
  
  type CurrencyInfo = {
  name: string;
  icon: string;
};

export const getCurrencyInfo = (symbol: string): CurrencyInfo => {
  const key = symbol?.toUpperCase() as keyof typeof CURRENCY_MAP;

  return (
    CURRENCY_MAP[key] ?? {
      name: key,
      icon: '',
    }
  );
};


import unstoppableLogo from '../../../public/domain/ud.svg'
import bonfidaLogo from '../../../public/domain/bonnfida.svg'
import ensLogo from '../../../public/domain/ethereum.svg'
import arbLogo from '../../../public/domain/arb.svg'
import bnbLogo from '../../../public/domain/bnb.svg'
import avaxLogo from '../../../public/domain/avax-domain.svg'
import tezosLogo from '../../../public/domain/tezos.svg'
import aptLogo from '../../../public/domain/apt.svg'
import tonLogo from '../../../public/domain/ton_symbol.png'
import boxLogo from '../../../public/domain/box_icon.png'
import starknetLogo from '../../../public/domain/starknet_icon.png'
import freenameLogo from '../../../public/domain/freename.svg'

export type DomainProviderKey =
  | 'UD'
  | 'ENS'
  | 'Arbitrum'
  | 'BinanceSmartChain'
  | 'Bonfida'
  | 'Tezos'
  | 'Aptos'
  | 'Ton'
  | 'Box'
  | 'Starknet'
  | 'Freename'

export interface DomainProvider {
  label: string
  provider: DomainProviderKey
  image: any
  colorName: string
}

export const DOMAIN_PROVIDERS: DomainProvider[] = [
  { label: 'Unstoppable Domains', image: unstoppableLogo, provider: 'UD',colorName: '#7e45e5' },
  { label: 'Ethereum Name Service', image: ensLogo, provider: 'ENS',colorName: '#60aaf5' },
  { label: 'Arbitrum', image: arbLogo, provider: 'Arbitrum',colorName: '#1a71b1' },
  { label: 'Binance', image: bnbLogo, provider: 'BinanceSmartChain',colorName: '#ffc300' },
  { label: 'Bonfida', image: bonfidaLogo, provider: 'Bonfida',colorName: '#000' },
  { label: 'Tezos', image: tezosLogo, provider: 'Tezos',colorName: '#14216a' },
  { label: 'Aptos', image: aptLogo, provider: 'Aptos',colorName: '#000' },
  { label: 'TON', image: tonLogo, provider: 'Ton',colorName: '#0098ea' },
  { label: 'Box', image: boxLogo, provider: 'Box',colorName: '#000' },
  { label: 'Starknet', image: starknetLogo, provider: 'Starknet',colorName: '#19aa6e' },
  { label: 'Freename', image: freenameLogo, provider: 'Freename',colorName: '#4144c0' }

    //   background: #e6eaf8;
    // font-size: 15px !important;
    // color: rgb(52, 65, 184);
    // margin-left: 10px;
]

export const getDomainProvider = (provider: DomainProviderKey) =>
  DOMAIN_PROVIDERS.find(p => p.provider === provider)

export const getProviderLogo = (provider: DomainProviderKey) =>
  getDomainProvider(provider)?.image

export const getProviderLabel = (provider: DomainProviderKey) =>
  getDomainProvider(provider)?.label

export const getProviderColor = (provider: DomainProviderKey) =>
  getDomainProvider(provider)?.colorName

export const getAllDomainProviders = () => DOMAIN_PROVIDERS

